FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /build

COPY Directory.Build.props .
COPY Directory.Packages.props .
COPY nuget.config .

COPY src/Application/Application.csproj src/Application/Application.csproj
RUN dotnet restore src/Application

COPY 